name: Blob storage website CI

on:
    push:
        branches: [ main ]
        paths:
        - Platform/client/*
        - .github/workflows/frontend.yml
    workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2

    - name: Build
      run: |
        cd Platform/client
        unset CI
        export REACT_APP_BASE_URL="https://climateappapi.azurewebsites.net"
        npm install
        npm run build
        ls

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            ls
            cd Platform/client/build
            az storage blob upload-batch --account-name climatehackathondatalake --auth-mode key -d '$web' -s .
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()

